config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :dummy_user
  resources :likes, only: %i[create destroy]
  resources :home do 
    collection do 
      get :confirmation
    end
  end
  resources :suggestions, only: %i[index create destroy]
  resources :posts do
    collection do
      get :pending
    end
    member do
      patch :publish
      delete :remove
      patch :set_status
    end
    resources :comments, only: %i[create update destroy]
    resources :suggestions do
      member do
        patch :apply
      end
    end
  end
  root 'posts#index'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent, class_name: :Comment, optional: true

  has_many_attached :files
  has_many :comments, dependent: :destroy, foreign_key: :parent_id
  has_many :likes, as: :likeable, dependent: :destroy

  validates :body, presence: true
  validates :files, file_size: { less_than_or_equal_to: 4.megabytes, message: I18n.t(:invalid_file_size) },
                    file_content_type: { allow: ['image/jpeg', 'image/jpg', 'image/png'],
                                         message: I18n.t(:invalid_file_format) }
  
  scope :active, -> { where(status: [nil, 'reported']) }
  scope :top, -> { where(parent_id: nil) }
  scope :reported, -> { where(status: 'reported') }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[update destroy]

  def create
    @comment = current_user.comments.new(comment_params.merge(post_id: params[:post_id]))
    flash[:alert] = if @comment.save
                      I18n.t(:comment_created)
                    else
                      @comment.errors.full_messages.to_sentence
                    end
    redirect_to post_path(params[:post_id])
  end

  def update
    authorize @comment
    @comment.status = params[:status]
    flash[:alert] = @suggestion.errors.full_messages.to_sentence unless @comment.save
    redirect_to post_path(params[:post_id])
  end

  def destroy
    authorize @comment
    flash[:alert] = if @comment.destroy
                      I18n.t(:comment_deleted)
                    else
                      @comment.errors.full_messages.to_sentence
                    end
    redirect_to post_path(params[:post_id])
  end

  private

  def set_comment
    @comment = Comment.find_by(id: params[:id])
    return unless @comment.nil?

    flash[:notice] = I18n.t(:resource_not_found)
    redirect_to posts_path
  end

  def comment_params
    params.require(:post).permit(:body, :parent_id, files: [])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<ul class='list-group'>
  <li class='list-group-item comment'>

    <!-- Comment details -->
    <strong><%= comment.user.email %>: </strong><%= comment.body %>
    <span>
      <p class='card-text'>
        <small class='text-muted'>Posted <%= time_ago_in_words(comment.created_at) %> ago </small>
      </p>

      <!-- Cloudinary files -->
      <% if comment.files.attached? %>
        <% comment.files.each do |file| %>
            <%= cl_image_tag file.key, :width=>150, :crop => 'fill', :cloud_name => Rails.application.credentials.cloudinary[:cloud_name] %>
        <% end %><br/><br/>
      <% end %>

      <!-- Current user can delete their comment else if not theirs, report it -->
      <% if current_user.id == comment.user.id %>  
        <%= link_to 'Delete', post_comment_path(comment.post_id,comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%= link_to 'Report', post_comment_path(comment.post_id,comment.id, status: 'reported'), method: :patch, data: { confirm: 'Are you sure?' } %>
      <% end %><br/><br/>

      <!-- Reply comment -->
      <a class='comment-form-display' href='#'>Reply</a>
      <div class='comment-form'>
        <%= render 'comments/form', locals: {post: @post, parent: @parent = comment} %>
      </div>

      <%= render partial: 'likes/button', locals: { likeable: comment, like: current_user.likes.find_by(likeable: comment) } %>

      <div class='sub-comment'>
        <%= render comment.comments.active %>
      </div>
    </span>

  </li><br/>
</ul>

app/views/comments/_form.html.erb
<%= form_with(model: @post, local: true, url: post_comments_path(@post.id), method: :post) do |form| %>
 
  <div class='form-group'>
    <%= form.text_field :body, class:'form-control', placeholder: 'Add a comment', :required => true %>
  </div>

  <% unless @parent.nil? %>
    <%= form.hidden_field :parent_id, value: @parent.id %>
  <% end %><br/>

  <div class='form-group'>
    <%= form.label :attachments, class:'form-label' %>
    <%= form.file_field :files, class:'form-control', 
        accept: 'image/jpg, image/jpeg, image/png', 
        multiple: true %>
  </div><br/>

  <div class='form-group'>
    <%= form.submit 'Post', class:'btn btn-primary' %>
  </div><br/>

<% end %>

app/views/comments/_reported.html.erb
<% if comments.any? %>
  <ul class='list-group'>
    <% comments.each do |comment|%>
      <li class='list-group-item'><strong><%= comment.user.email %>: </strong><%= comment.body %>
        <span>
          <div class='report-approval'>
            <%= link_to 'Accept', post_comment_path(comment.post_id,comment.id, status: 'hidden'), method: :patch, data: { confirm: 'Are you sure?' }, class:'btn btn-success' %>
            <%= link_to 'Deny', post_comment_path(comment.post_id,comment.id, status: nil), method: :patch, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          </div>
        </span>
      </li>
    <% end %>
  </ul>
<% else %>
  <blockquote class='blockquote'>
    <p>No reported comments</p>
  </blockquote>
<% end %>