config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :dummy_user
  resources :likes, only: %i[create destroy]
  resources :home do 
    collection do 
      get :confirmation
    end
  end
  resources :suggestions, only: %i[index create destroy]
  resources :posts do
    collection do
      get :pending
    end
    member do
      patch :publish
      delete :remove
      patch :set_status
    end
    resources :comments, only: %i[create update destroy]
    resources :suggestions do
      member do
        patch :apply
      end
    end
  end
  root 'posts#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  has_many :suggestions, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :files
  has_many :comments, dependent: :destroy

  enum status: { UNPUBLISHED: 0, PUBLISHED: 1 }

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 30 }
  validates :files, file_size: { less_than_or_equal_to: 4.megabytes, message: I18n.t(:invalid_file_size) },
                    file_content_type: { allow: ['image/jpeg', 'image/jpg', 'image/png'],
                                         message: I18n.t(:invalid_file_format) }

  scope :active, -> { where(report_status: [nil, 'reported']) }

  def apply_suggestion(suggestion)
    description.gsub!(/#{suggestion.to_replace}/i, suggestion.replacement)
    save!
  end

  def publish_post
    self.status = 1
    self.published_at = Time.zone.now
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy publish remove set_status]

  # GET /posts or /posts.json
  def index
    @posts = Post.PUBLISHED.active.order(id: :desc).includes(:user).page(params[:page]).per(4)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    redirect_to posts_path if @post.report_status == 'hidden'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end    
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: I18n.t(:post_create) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: I18n.t(:post_update) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: I18n.t(:post_destroy) }
    end
  end

  def set_status
    @post.report_status = params[:status]
    flash[:alert] = @suggestion.errors.full_messages.to_sentence unless @post.save
    redirect_to post_path(params[:id])
  end

  def pending
    @pending_posts = if current_user.role == 'moderator'
                       Post.UNPUBLISHED.order(id: :desc).includes(:user).page(params[:page]).per(4)
                     else
                       current_user.posts.UNPUBLISHED.order(id: :desc).includes(:user).page(params[:page]).per(4)
                     end
  end

  def publish
    @post.publish_post
    flash[:alert] = if @post.save
                      I18n.t(:post_published)
                    else
                      @post.errors.full_messages.to_sentence
                    end
    redirect_to pending_posts_path
  end

  def remove
    flash[:alert] = if @post.destroy
                      I18n.t(:post_destroy)
                    else
                      @post.errors.full_messages.to_sentence
                    end
    redirect_to pending_posts_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by(id: params[:id])
    return unless @post.nil?

    flash[:notice] = I18n.t(:resource_not_found)
    redirect_to posts_path
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :user_id, files: [])
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(post.errors.count, 'error') %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :title, class:'form-label' %>
    <%= form.text_field :title, class:'form-control', :required => true %>
  </div><br/>

  <div class='form-group'>
    <%= form.label :description, class:'form-label' %>
    <%= form.text_field :description, class:'form-control', :required => true %>
  </div><br/>

  <div class='form-group'>
    <%= form.label :files, class:'form-label' %>
    <%= form.file_field :files, class:'form-control', 
        accept: 'image/jpg, image/jpeg, image/png', 
        multiple: true %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %><br/>

  <div class='form-group'>
    <%= form.submit class:'btn btn-secondary' %>
  </div><br/>
  
<% end %>

app/views/posts/_post.html.erb
<div class='card mb-3' style='max-width: 90%;'>
<div class='row g-0'>
  <div class='col-md-12'>
    <div class='card-body'>
      
      <!-- Post details -->
      <h5 class='card-title'><%= post.title %></h5>
      <p><b>Posted by: </b><%= post.user.email %></p>
      <p class='card-text'><%= post.description %></p>
      <p class='card-text'><small class='text-muted'>Posted <%= post.published_at ? (time_ago_in_words(post.created_at)) : time_ago_in_words(post.created_at)  %> ago </small></p>
      <p class='card-text'><small class='text-muted'>Last Updated <%= time_ago_in_words(post.updated_at) %> ago </small></p>
  
      <!-- Cloudinary files -->
      <% if post.files.attached? %>
        <% post.files.each do |file| %>
          <%= cl_image_tag file.key, :width=>150, :crop=>'fill', :cloud_name => Rails.application.credentials.cloudinary[:cloud_name] %>
        <% end %>
      <% end %><br/><br/>
  
      <% if page == 'index' %>
        <%= link_to 'Show', post, class:'btn btn-primary' %>
      
        <!-- Moderator can remove posts -->
        <% if current_user.role == 'moderator' %><br/><br/>
          <%= link_to 'Remove', remove_post_path(post), method: :delete, class:'btn btn-danger',  data: { confirm: 'Are you sure?' } %>
        <% end %>
  
      <!-- Publish or unpublish posts for moderator -->
      <% elsif page == 'pending' %>
        <% if current_user.role == 'moderator' %><br/><br/>
          <%= link_to 'Publish', publish_post_path(post), method: :patch, class:'btn btn-success',  data: { confirm: 'Are you sure?' } %><br/><br/>
          <%= link_to 'Remove', remove_post_path(post), method: :delete, class:'btn btn-danger',  data: { confirm: 'Are you sure?' } %>
        <% end %>
  
      <% else %>
        <!-- Show reported posts for the moderator -->
        <% if current_user.role == 'moderator' && post.report_status == 'reported' %>
          <%= render partial: 'reported', locals: {post: post} %><br/><br/>
        <% end %>
  
        <!-- Show post suggestions to post owner -->
        <% if current_user.id == post.user_id && post.PUBLISHED? %>
          <a class='suggestions-display' href='#'>Show Suggestions</a>
          <div class='suggestion-form'>
            <%= render partial: 'suggestions/suggestions', locals: {post: post} %>
          </div><br/><br/>
          <%= link_to 'Edit', edit_post_path(post), class:'btn btn-warning' %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          
        <!-- Add suggestions if post not owned -->
        <% elsif current_user.id != post.user_id %>
          <a class='suggestion-form-display' href='#'>Add Suggestion</a>
          <div class='suggestion-form'>
          <%= render partial: 'suggestions/form', locals: {post: post} %>
          </div><br/><br/>
          <%= link_to 'Report', set_status_post_path(post.id, status: 'reported'), method: :patch, data: { confirm: 'Are you sure?' } %>
        
        <% end %>
  
    <% end %>
    
    </div>
  </div>
</div>
</div>

app/views/posts/_reported.html.erb
<ul class='list-group'>
  <li class='list-group-item'>Post has been reported
    <span>
      <div class='report-approval'>
        <%= link_to 'Accept', set_status_post_path(post.id, status: 'hidden'), method: :patch, data: { confirm: 'Are you sure?' }, class:'btn btn-success' %>
        <%= link_to 'Deny', set_status_post_path(post.id, status: nil), method: :patch, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
      </div>
    </span>
  </li>
</ul>

app/views/posts/edit.html.erb
<h1>Edit Post</h1><br/>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:'btn btn-primary' %>

app/views/posts/index.html.erb
<h2>Recent posts</h2><br/>

<% @posts.each do |post| %>
  <%= render partial: 'posts/post', locals: { post: post, page: 'index' } %>
<% end %><br>

<%= link_to 'New Post', new_post_path, class:'btn btn-primary' %><br><br><br>

<div class='pagination'>
  <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:'btn btn-primary' %>

app/views/posts/pending.html.erb
<h2>Pending posts</h2><br/>

<% @pending_posts.each do |post| %>
  <%= render partial: 'posts/post', locals: { post: post, page: 'pending' } %>
<% end %><br/>

<%= link_to 'Back', posts_path, class:'btn btn-primary' %><br/><br/>

<!-- Pagination -->
<div class='pagination'>
  <%= paginate @pending_posts, theme: 'twitter-bootstrap-4' %>
</div>

app/views/posts/show.html.erb
<%= render partial: 'posts/post', locals: { post: @post, page: 'show' } %>

<!-- Comments sections -->

<% if @post.PUBLISHED? %>

  <%= render partial: 'likes/button', locals: { likeable: @post, like: current_user.likes.find_by(likeable: @post) } %><br/>
  <h3>Comments</h3><hr/><br/>

  <!-- Show reported comments for the post owner -->
  <% if current_user.id == @post.user_id && @post.PUBLISHED? %>
    <a class='reported-display' href='#'>Show Reported Comments</a>
    <div class='suggestion-form'>
      <%= render partial:'comments/reported', locals: {comments: @post.comments.reported} %>
    </div><br/><br/>
  <% end %>

  <!-- Show all comments -->
  <%= render @post.comments.where(parent_id: nil).active.includes(:user).order(id: :desc) %><br/>

  <!-- Add comment form -->
  <h3>Add comment</h3><hr/><br/>
  <%= render 'comments/form', locals: {post: @post, parent: @parent = nil} %>

<% end %><br/>

<%= link_to 'Back', posts_path, class:'btn btn-primary' %><br/><br/>