config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :dummy_user
  resources :likes, only: %i[create destroy]
  resources :home do 
    collection do 
      get :confirmation
    end
  end
  resources :suggestions, only: %i[index create destroy]
  resources :posts do
    collection do
      get :pending
    end
    member do
      patch :publish
      delete :remove
      patch :set_status
    end
    resources :comments, only: %i[create update destroy]
    resources :suggestions do
      member do
        patch :apply
      end
    end
  end
  root 'posts#index'
end

app/models/suggestion.rb
# frozen_string_literal: true

class Suggestion < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :to_replace, presence: true
  validates :replacement, presence: true
end

app/controllers/suggestion_controller.rb
class SuggestionController < ApplicationController
  def create
    @suggestion = current_user.suggestions.new(suggestion_params.merge(post_id: params[:post_id]))
    unless @suggestion.save
      flash[:alert] = @suggestion.errors.full_messages.to_sentence
    end
    redirect_to post_path(params[:post_id])
  end

  def apply
    @post = Post.find(params[:post_id])
    @suggestion = Suggestion.find(params[:id])
    @post.apply_suggestion(@suggestion)
    @suggestion.destroy
    redirect_to post_path(params[:post_id])
  end

  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def suggestion_params
    params.require(:post).permit(:to_replace, :replacement)
  end
end

app/controllers/suggestions_controller.rb
# frozen_string_literal: true

class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: %i[apply destroy]

  def index
    @suggestions = current_user.suggestions
  end

  def create
    @suggestion = current_user.suggestions.new(suggestion_params.merge(post_id: params[:post_id]))
    flash[:alert] = @suggestion.errors.full_messages.to_sentence unless @suggestion.save
    redirect_to post_path(params[:post_id])
  end

  def apply
    @post = Post.find(params[:post_id])
    @post.apply_suggestion(@suggestion)
    flash[:alert] = if @post.save
                      I18n.t(:suggestion_applied)
                    else
                      I18n.t(:suggestion_not_applied)
                    end
    @suggestion.destroy
    redirect_to post_path(params[:post_id])
  end

  def destroy
    flash[:alert] = if @suggestion.destroy
                      I18n.t(:suggestion_destroy)
                    else
                      @suggestion.errors.full_messages.to_sentence
                    end
    redirect_to request.referer
  end

  private

  def set_suggestion
    @suggestion = Suggestion.find_by(id: params[:id])
    return unless @suggestion.nil?

    flash[:notice] = I18n.t(:resource_not_found)
    redirect_to posts_path
  end

  def suggestion_params
    params.require(:post).permit(:to_replace, :replacement)
  end
end

app/helpers/suggestion_helper.rb
# frozen_string_literal: true

module SuggestionHelper
end

app/views/suggestions/_form.html.erb
<%= form_with(model: @post, local: true, url: post_suggestions_path(@post.id), method: :post) do |form| %>
 
  <div class='form-group'>
    <%= form.label :'To replace', class:'form-label' %>
    <%= form.text_field :to_replace, class:'form-control', placeholder: 'to replace ...', :required => true %>
  </div><br/>
  
  <div class='form-group'>
    <%= form.label :'Replacement', class:'form-label' %>
    <%= form.text_field :replacement, class:'form-control', placeholder: 'replacement ...', :required => true %>
  </div><br/>

  <div class='form-group'>
    <%= form.submit 'Submit', class:'btn btn-primary' %>
  </div><br/>

<% end %>

app/views/suggestions/_suggestions.html.erb
<% if @post.suggestions.any? %>
  <table class='table'>
    <thead>
      <tr>
        <th scope='col'>Suggested by</th>
        <th scope='col'>To Replace</th>
        <th scope='col'>Replacement</th>
        <th scope='col'>Handle</th>
      </tr>
    </thead>
    <tbody>
      <% @post.suggestions.each do |suggestion| %>
        <tr>
          <td><%= suggestion.user.email %></td>
          <td><%= suggestion.to_replace %></td>
          <td><%= suggestion.replacement %></td>
          <td><%= link_to 'Approve', apply_post_suggestion_path(@post, suggestion.id), method: :patch, data: { confirm: 'Are you sure?' }, class:'btn btn-success'%> <%= link_to 'Deny', post_suggestion_path(@post,suggestion.id),  method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <blockquote class='blockquote'>
    <p>No suggestions for this post</p>
  </blockquote>
<% end %>

app/views/suggestions/by_user.html.erb
<h3>Your active suggestions</h3><hr/><br/>

<% if @suggestions.any? %>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">Post owner</th>
        <th scope="col">To Replace</th>
        <th scope="col">Replacement</th>
        <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        <% @suggestions.each do |suggestion| %>
        <tr>
        <td><%= suggestion.post.user.email %></td>
        <td><%= suggestion.to_replace %></td>
        <td><%= suggestion.replacement %></td>
        <td><%= link_to 'Remove', remove_suggestion_path(suggestion.id),  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% else %>
  <blockquote class="blockquote">
    <p>You do not have any active suggestions</p>
  </blockquote>
<% end %>

app/views/suggestions/index.html.erb
<h3>Your active suggestions</h3><hr/><br/>

<% if @suggestions.any? %>
  <table class='table'>
    <thead>
      <tr>
        <th scope='col'>Post owner</th>
        <th scope='col'>To Replace</th>
        <th scope='col'>Replacement</th>
        <th scope='col'>Handle</th>
      </tr>
    </thead>
    <tbody>
      <% @suggestions.each do |suggestion| %>
        <tr>
          <td><%= suggestion.post.user.email %></td>
          <td><%= suggestion.to_replace %></td>
          <td><%= suggestion.replacement %></td>
          <td><%= link_to 'Remove', post_suggestion_path(suggestion.post_id,suggestion.id),  method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <blockquote class='blockquote'>
    <p>You do not have any active suggestions</p>
  </blockquote>
<% end %>