config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :dummy_user
  resources :likes, only: %i[create destroy]
  resources :home do 
    collection do 
      get :confirmation
    end
  end
  resources :suggestions, only: %i[index create destroy]
  resources :posts do
    collection do
      get :pending
    end
    member do
      patch :publish
      delete :remove
      patch :set_status
    end
    resources :comments, only: %i[create update destroy]
    resources :suggestions do
      member do
        patch :apply
      end
    end
  end
  root 'posts#index'
end

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-primary'>
  <div class='container-fluid'>
    <%= link_to 'Blog App', root_path, class:'navbar-brand' %>
    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarNav'>
      <ul class='navbar-nav'>
        <% if current_user %>
          <li class='nav-item'>
            <%= link_to 'Posts', posts_path ,class:'nav-link'%>
          </li>
          <li class='nav-item'>
            <%= link_to 'Pending', pending_posts_path, class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'My Suggestions', suggestions_path, class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
          </li>
          <% if current_user.role == 'admin'%>
            <li class='nav-item'>
              <%= link_to 'Admin', rails_admin_path, class:'nav-link' %>
            </li>
          <% end %>
        <% else %>
          <li class='nav-item'>
            <%= link_to 'Log In', new_user_session_path, class:'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <br/>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% elsif notice %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  
  </body>
  
</html>